### ISSUE TITLE
Clarify semantics of updating `@data` vs. changed data

### ISSUE THREAD

**Issue by simonihmig** [CrowdStrike/ember-headless-form#130]
> This issue has its origins in #117, some bits are copied here to focus the discussion only on the topic of what should happen when `@data` or a tracked property (`@data.foo`) is updated, while the form might have "dirty" data itself.

headless-form takes the approach of being strict about DDAU, even though in the case of forms there are some more or less valid cases for allowing two-way bindings maybe. But we don't do this, so the user will only get the new data by receiving it from `@onSubmit`. That means we have the original (unaltered) data coming from the caller as `@data`, and we have an internal data object that tracks the "dirty" data (user has filled in some fields, making those diverge from `@data`). What is displayed in the form is then basically the union of these, with any dirty value overriding the original one. Resetting the form then basically means resetting the internal data to an empty object, so all of `@data` is visible again (for forms used for "create" operations this is mostly just an empty object).

Im trying to incorporate the different cases of the state of the input (pristine - has never been touched by the user - vs. dirty - user has entered a different value than the initial one) and the action that is happening.

So the question we have to answer is: what would a user expect to happen? I.e. what should the `?` be in:

|                             | `@data.foo` is updated (`@tracked`)               | `@data` is reassigned             |
|-----------------------------|-----------------------------------------------|---------------------------------|
| input[name=foo] is pristine | ?               | ? |
| input[name=foo] is dirty    | ? | ?                               |

## 1. data gets copied initially, loses connection with `@data` afterwards

|                             | `@data.foo` is updated (`@tracked`)               | `@data` is reassigned             |
|-----------------------------|-----------------------------------------------|---------------------------------|
| input[name=foo] is pristine | input is not updated (keeps original in value)     | input is not updated (keeps original in value) |
| input[name=foo] is dirty    | input is not updated  (keeps filled in value) | input is not updated  (keeps filled in value)                             |

## 2. changed data (dirty fields) is preserved, only untouched fields reflect `@data` changes

|                             | `@data.foo` is updated (`@tracked`)               | `@data` is reassigned             |
|-----------------------------|-----------------------------------------------|---------------------------------|
| input[name=foo] is pristine | input is updated with `@data.foo`               | input is updated with `@data.foo` |
| input[name=foo] is dirty    | input is not updated  (keeps filled in value) | input is not updated  (keeps filled in value)                               |

FWIW, I think this is how `ember-changeset` behaves, having a similar concept of changed vs. original data

## 3. when `@data` is updated, any local changes (dirty fields) are discarded

|                             | `@data.foo` is updated (`@tracked`)               | `@data` is reassigned             |
|-----------------------------|-----------------------------------------------|---------------------------------|
| input[name=foo] is pristine |input is updated with `@data.foo`    | input is updated with `@data.foo` |
| input[name=foo] is dirty    | input is updated with `@data.foo` | input is updated with `@data.foo`                           |

This would allow the use case of resetting (#117) to be covered by a simple `this.data = {}`.

## 4. Only reassigning `@data` is discarding local changes

|                             | `@data.foo` is updated (`@tracked`)               | `@data` is reassigned             |
|-----------------------------|-----------------------------------------------|---------------------------------|
| input[name=foo] is pristine | input is updated with `@data.foo`    | input is updated with `@data.foo` |
| input[name=foo] is dirty    | input is not updated  (keeps filled in value) | input is updated with `@data.foo`                           |

This would allow the use case of resetting (#117) to be covered by a simple `this.data = {}`, while preserving local changes when only properties have been updated. Could this be useful?

## 5. Make this configurable

We could provide some options to choose between different modes (we already have `@dataMode`). But having to support multiple cases - some of which are probably not trivial to implement themselves, but the complexity might explode when having to support multiple ones in parallel - comes at a cost.

**Comment by herzzanu** [comment]
Thanks for opening this, it makes more sense indeed. I wanted to throw into the mix the idea that when resetting the form state we probably want to reset any possible invalid state as well as clean error messages. So resetting should somehow be done internally. Did you already take this into account? Do you have any thoughts on it?

**Comment by simonihmig** [comment]
Yeah, this makes sense, and I had it in my mind in general. But let's keep the reset use case out of this discussion here. we can discuss it in #117 though! :wink:

**Comment by nicolechung** [comment]
I think #3 (`when @data is updated, any local changes (dirty fields) are discarded`) is the most common default behavior.

## Blank forms

1. User opens form
- `@data` is empty
- internal data is set as the form is filled
2. Form is submitted
- `@data` goes from empty to full
- internal data is reset to empty (local changes are discarded)

## Blank forms, reset before submitting

1. User opens form
- `@data` is empty
- internal data is set as the form is filled
2. Form is reset
- `@data` is (re)set to empty
- internal data is reset to empty (local changes are discarded)

## Pre-filled form from server data

1.  User opens pre-filled form
- `@data` pre-filled from server
- internal data is set as form is edited
2. Form is submitted
- `@data` goes from initial to `@data` plus internal data changes
- internal data is reset to empty (local changes are discarded)

## Pre-filled form from server data, and then form is reset before submitting

1.  User opens pre-filled form
- `@data` pre-filled from server
- internal data is set as form is edited
2. Form is reset
- `@data` is reset to it's initial `@data`
- internal data is reset to empty (local changes are discarded)

Those are the situations I am most familiar with. So to me #3 seems the most likely.

I think #5 (making it configurable) might be an option too, but only if there are situations aside from these 4 I can think of.

**Comment by averydev** [comment]
Thanks for the discussion @simonihmig!

I'm all for #3 here.

Having changes to underlying data reset any dirty changes made to the form would be the most in line with DDAU, and yield the most predictable behavior. I'm having a hard time coming up with a use case where another process made a change to an attribute, but i still wanted the dirty change in a form. I can only imagine this being a source of confusion / bugs. 

If you don't want the data in the form to update, all you have to do is... not change the data :)
That should be well in hand by the dev at that time, and the business logic should be pretty simple to get the result they want.

I haven't thought about this long and hard, but it seems like with #4, instead of throwing away only the data that changed it'd be a chore to not throw away *all* changes. You'd do something like get the current data out of the form, them merge it with the new data, and set the data again. Seems like a lot of work for what for me has been the primary use case.

![image](https://user-images.githubusercontent.com/477027/236924644-5eb30722-48fe-46d8-9f47-4b813f1a6367.png)

**Comment by sukima** [comment]
I did a little research on FireFox forms and how it handles the same problem in Vanilla HTML.

[Playground to experiment](https://tritarget.org/fiddles/#DwQgIg8gwgKgmgBQKIAIAWAXAtgGwHwBQwmuKOAhgHYDmAvAEQCml9hxj5AJm1oxuSgDGacgCcAznwYBVGADEAtAA5WRDAEsMORngBqVdTgooAZgHtRWcSk7rRGAJ4osVctUa9KGYAHoNWnQIicUFRdQAHDBRHcMYGLDNOAFdtVXUscIsogBJTUTMsFAByH0FOSh9xdPDtBU4CgDoAK3EigG4gnx8UGDRGUUYUdWsBSVjRcg0zShQAIz4Ad0ZmFAADBoA3chwkwdpVlCpOFEkMAEEMDDDZpIxGAAoirZ3GIoBKAi6UAGU+DRpon0UJttrsUAtDDgUJQzFFyCYTIxBFEMEDnmDUYNzJYUANTtYMGYGp9ugB1NCGQanC5XdQ3O6PdGvN7gyEEcjiByUQSmJLcqYzESUTjaMCTchgMwLSj3FkAbwIKFMFkOC3ImhQ920UUYG2YUTMJhQ2QanHFkulDWmDWEVHcso+SqVX1+l3UANRw1ZRhQEAAcgAZOBCchJSSAwbu8K3RVOr4mdSMHDHQkoJLhM13FAASTkQyiXoQACVs98YNm-UhY0qTQmk5wGtTLtdbg8nqDXgAaFC6-UNfiidwYEEvN4dAC+QQ5XJ5Jj5yPU03QR203ySsywmllKAVSuxqvVUS1fB7eq8KENxoaWAccgsWCtlEb683GAdO+rZBPeJSUVo0MYBYUDvSwxX4e5ey8fsxCHMcgidU8+3CAYzwwMBGBMUMcDfOCEJNH9sJHMF-wI4ch0ecwzHeDolUnScCCFEVGDAiUpRlODGNXF8tzg3wQjCSI2B8PouDYWZEgcNhsUKdROHiW973oaEzGeWTJkCJVgHCQgEOACh5ihbEGDrZNWDkRNkwALl8fSkx0p1gCjW4hjk+gTM4JTKHIXhjLMMwlKZXyzFmMRVE0nxtNjLT7M0+lCRmGI4noPE+FYItGFOXw4umGKUGAbKEocWIGHEbiMFYNcN00LLbni+zfEizTGoc2zDIsBhSIqsrcQy39rJ8VrcuAMxbmjAtXM6vBfBGjAxvqiKhOktg0FENhmr08gDOVUQGEzVjpVYFiUAtGYmX6waoqc8bdvNNjPO8pK9pOgKOyCkLRFUBqhPEzhJKIYTsHwIA)

Turns out that the browser already has a concept of dirty/pristine under the hood. If the user enters a different value as the `value="…"` attribute it will remain even with a data-down change. But if the data-down change affects a field that is pristine it will update.

This fits the logic:

<h2 dir="auto">2. changed data (dirty fields) is preserved, only untouched fields reflect <code class="notranslate">@data</code> changes</h2>


  | @data.foo is updated (@tracked) | @data is reassigned
-- | -- | --
input[name=foo] is pristine | input is updated with @data.foo | input is updated with @data.foo
input[name=foo] is dirty | input is not updated  (keeps filled in value) | input is not updated  (keeps filled in value)

It would be my preference and I presume that of other developers that this behavior remain as expected to match what browsers already offer. I suspect that users would also feel the same.

**Comment by simonihmig** [comment]
After this discussion here (and internally), I am leaning towards the following...

First of all, I think we need to separate the need to support a _use case_ from what should happen when `@data` changes (the original question here), as we can support a use case in a different way also.

It seems we definitely have a strong case to support `#3` here, but also `#2` has some support. I feel the latter is especially the case as there is some similar behaviour we see in other cases of having original vs. dirty/pristine data:
* as mentioned above, `ember-changeset` also works that way
* and as @sukima mentioned, there is some similarity also with native form behaviour (`value` attribute vs. value)

With that, I would suggest the following:
* when `@data` changes, the form behaves as laid out in `#2`
* we still can and need to support the use case of "resetting", so we can have some `reset` action (yielded to the inner template block and/or some "action down" approach as discussed in #117). So when `reset()` is called, it basically means to throw away all dirty data, i.e. the form will display again what it gets as `@data`
* so when you just want to reset the data to what `@data` is representing, then you just call `reset()` obviously. But when you want to completely change the form data, e.g. because the user has selected a different model whose data flows into the form, then you would make `@data` update with the new form data _and_ call `reset()`, to wipe out any previous dirty data, thereby supporting case `#3`

What do you think, does that make sense?

**Comment by herzzanu** [comment]
@simonihmig Thanks for summarizing this, looks like we're heading into a good direction, given all the feedback above. One simple question, to clarify things in my mind. When you mention "`@data` changes", do you mean the whole `@data` object is reassigned or do you refer to changes within the `@data` object?

Otherwise what you summarized above makes sense to me 👏

**Comment by simonihmig** [comment]
Closing this, `#2` is implemented in #132
